name: Publish

on:
  release:
    types: [ published ]

permissions:
  contents: 'write'
  id-token: 'write'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Build Client App
        working-directory: ./src/KafkaFlow.Admin.Dashboard/ClientApp
        run: |
          npm install
          npm run lint
          npm run build:prod

      - name: Pack
        run: dotnet pack ./src/KafkaFlow.sln -c Release /p:Version=${{ github.event.release.tag_name }} -o ./drop

      - name: Publish
        run: dotnet nuget push ./drop/**/*.nupkg --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${GITHUB_TOKEN} --skip-duplicate
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Version
        run: echo ${{ github.event.release.tag_name }}
